const recommendationTemplates = {
  certificates: {
    condition: (data) => data.certificates === 'printed',
    title: 'Switch to Digital Certificates',
    description: 'Replace printed certificates with digital PDF certificates. This reduces paper waste, printing costs, and carbon emissions from delivery.',
    impact: 85,
    priority: 'high',
    difficulty: 'easy',
    improvement: 8,
    sdg: 12,
  },
  water: {
    condition: (data) => data.water === 'plastic-bottles',
    title: 'Replace Plastic Bottles with Refill Stations',
    description: 'Install water refill stations and provide reusable bottles to participants. This eliminates single-use plastic waste significantly.',
    impact: 95,
    priority: 'high',
    difficulty: 'medium',
    improvement: 15,
    sdg: 6,
  },
  transport: {
    condition: (data) => data.transport === 'private',
    title: 'Encourage Public Transportation & Carpooling',
    description: 'Provide public transport passes and create a carpool matching system for attendees to reduce per-person carbon emissions.',
    impact: 80,
    priority: 'high',
    difficulty: 'medium',
    improvement: 12,
    sdg: 11,
  },
  food: {
    condition: (data) => data.food === 'disposable',
    title: 'Use Reusable or Biodegradable Serving Materials',
    description: 'Replace disposable plates and cutlery with reusable or compostable alternatives made from bamboo or plant-based materials.',
    impact: 75,
    priority: 'medium',
    difficulty: 'medium',
    improvement: 10,
    sdg: 12,
  },
  energy: {
    condition: (data) => data.energy === 'high',
    title: 'Adopt Renewable Energy Sources',
    description: 'Use solar-powered generators, energy-efficient LED lighting, and smart power strips to reduce event energy consumption.',
    impact: 90,
    priority: 'high',
    difficulty: 'hard',
    improvement: 18,
    sdg: 7,
  },
  waste: {
    condition: (data) => data.wasteSegregation === 'not-available',
    title: 'Implement Waste Segregation Stations',
    description: 'Set up clearly labeled bins for recyclables, compost, and landfill waste. Train volunteers to guide attendees on proper disposal.',
    impact: 70,
    priority: 'medium',
    difficulty: 'easy',
    improvement: 10,
    sdg: 12,
  },
  registration: {
    condition: (data) => data.registration === 'paper',
    title: 'Go Fully Digital with Registration',
    description: 'Eliminate paper forms by using QR code-based digital check-ins and online registration systems.',
    impact: 60,
    priority: 'medium',
    difficulty: 'easy',
    improvement: 5,
    sdg: 12,
  },
  marketing: {
    condition: (data) => data.marketing === 'printed',
    title: 'Shift to Digital Marketing',
    description: 'Replace printed posters and flyers with social media campaigns, digital banners, and email marketing.',
    impact: 55,
    priority: 'low',
    difficulty: 'easy',
    improvement: 5,
    sdg: 12,
  },
  'solar-power': {
    condition: (data) => !data.initiatives?.includes('solar-power'),
    title: 'Install Solar Power Systems',
    description: 'Power your event using solar panels and battery storage. This drastically reduces grid energy dependency and carbon footprint.',
    impact: 92,
    priority: 'high',
    difficulty: 'hard',
    improvement: 20,
    sdg: 7,
  },
  'tree-plantation': {
    condition: (data) => !data.initiatives?.includes('tree-plantation'),
    title: 'Organize a Tree Plantation Drive',
    description: 'Offset event carbon emissions by planting trees. Each tree absorbs approximately 22kg of CO₂ per year.',
    impact: 88,
    priority: 'medium',
    difficulty: 'medium',
    improvement: 15,
    sdg: 15,
  },
  'carbon-offset': {
    condition: (data) => !data.initiatives?.includes('carbon-offset'),
    title: 'Implement Carbon Offset Program',
    description: 'Partner with certified carbon offset providers to neutralize unavoidable emissions from travel and energy use.',
    impact: 85,
    priority: 'medium',
    difficulty: 'medium',
    improvement: 12,
    sdg: 13,
  },
}

export function generateRecommendations(formData) {
  return Object.entries(recommendationTemplates)
    .filter(([, template]) => template.condition(formData))
    .map(([key, rec]) => ({
      id: key,
      ...rec,
    }))
    .sort((a, b) => b.impact - a.impact)
}
