import { calculateScores } from './sustainabilityEngine.js'
import { calculateCarbonImpact } from './carbonCalculator.js'
import { generateRecommendations } from './recommendations.js'
import { mapSDGImpact } from './sdgMapper.js'
import { getCertification } from './certification.js'
import { checkBadges } from './badges.js'

// Diverse sample events with different categories, scores, and scenarios
const sampleEvents = [
  {
    eventName: 'GreenTech Conference 2026',
    organization: 'GreenTech Innovations',
    location: 'Bangalore, India',
    category: 'conference',
    participants: '500',
    duration: '2',
    transport: 'public',
    water: 'refill-stations',
    food: 'biodegradable',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['solar-power', 'carbon-offset', 'tree-plantation', 'digital-invitations', 'waste-recycling'],
  },
  {
    eventName: 'University Climate Summit',
    organization: 'IIT Delhi',
    location: 'Delhi, India',
    category: 'college-fest',
    participants: '1200',
    duration: '3',
    transport: 'public',
    water: 'refill-stations',
    food: 'reusable',
    energy: 'medium',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['plastic-free', 'digital-invitations', 'waste-recycling', 'community-awareness'],
  },
  {
    eventName: 'Eco-Fest 2026',
    organization: 'Green Earth NGO',
    location: 'Mumbai, India',
    category: 'ngo-event',
    participants: '800',
    duration: '2',
    transport: 'carpool',
    water: 'reusable-bottles',
    food: 'biodegradable',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'hybrid',
    wasteSegregation: 'available',
    initiatives: ['tree-plantation', 'plastic-free', 'solar-power', 'carbon-offset', 'waste-recycling', 'reusable-decorations'],
  },
  {
    eventName: 'Corporate Sustainability Workshop',
    organization: 'Infosys Ltd',
    location: 'Pune, India',
    category: 'workshop',
    participants: '150',
    duration: '1',
    transport: 'carpool',
    water: 'reusable-bottles',
    food: 'reusable',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['solar-power', 'digital-invitations', 'waste-recycling'],
  },
  {
    eventName: 'National Tech Expo',
    organization: 'Tech Mahindra',
    location: 'Hyderabad, India',
    category: 'conference',
    participants: '2000',
    duration: '3',
    transport: 'private',
    water: 'plastic-bottles',
    food: 'disposable',
    energy: 'high',
    registration: 'paper',
    certificates: 'printed',
    marketing: 'printed',
    wasteSegregation: 'not-available',
    initiatives: [],
  },
  {
    eventName: 'Rural Education Camp',
    organization: 'Pratham Foundation',
    location: 'Rajasthan, India',
    category: 'ngo-event',
    participants: '200',
    duration: '5',
    transport: 'carpool',
    water: 'refill-stations',
    food: 'biodegradable',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['tree-plantation', 'community-awareness', 'plastic-free'],
  },
  {
    eventName: 'Startup Pitch Fest',
    organization: 'YC Alumni India',
    location: 'Gurugram, India',
    category: 'seminar',
    participants: '300',
    duration: '1',
    transport: 'hybrid',
    water: 'plastic-bottles',
    food: 'disposable',
    energy: 'medium',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'hybrid',
    wasteSegregation: 'available',
    initiatives: ['digital-invitations'],
  },
  {
    eventName: 'Community Clean-Up Drive',
    organization: 'Local Municipality',
    location: 'Chennai, India',
    category: 'community-gathering',
    participants: '600',
    duration: '1',
    transport: 'carpool',
    water: 'reusable-bottles',
    food: 'none',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['tree-plantation', 'waste-recycling', 'community-awareness', 'plastic-free'],
  },
  {
    eventName: 'AI & ML Hackathon',
    organization: 'Google Developer Groups',
    location: 'Bengaluru, India',
    category: 'hackathon',
    participants: '400',
    duration: '2',
    transport: 'public',
    water: 'refill-stations',
    food: 'biodegradable',
    energy: 'medium',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['solar-power', 'carbon-offset', 'digital-invitations', 'waste-recycling'],
  },
  {
    eventName: 'Traditional Arts & Culture Fest',
    organization: 'Ministry of Culture',
    location: 'Jaipur, India',
    category: 'cultural-event',
    participants: '1500',
    duration: '4',
    transport: 'private',
    water: 'plastic-bottles',
    food: 'disposable',
    energy: 'high',
    registration: 'paper',
    certificates: 'printed',
    marketing: 'printed',
    wasteSegregation: 'not-available',
    initiatives: [],
  },
  {
    eventName: 'Renewable Energy Summit',
    organization: 'IRENA Partners',
    location: 'Gandhinagar, India',
    category: 'conference',
    participants: '350',
    duration: '2',
    transport: 'carpool',
    water: 'refill-stations',
    food: 'biodegradable',
    energy: 'low',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'hybrid',
    wasteSegregation: 'available',
    initiatives: ['solar-power', 'carbon-offset', 'tree-plantation', 'plastic-free', 'waste-recycling', 'reusable-decorations'],
  },
  {
    eventName: 'Medical Camp for Rural Health',
    organization: 'AIIMS Outreach',
    location: 'Bihar, India',
    category: 'ngo-event',
    participants: '800',
    duration: '3',
    transport: 'public',
    water: 'reusable-bottles',
    food: 'biodegradable',
    energy: 'medium',
    registration: 'digital',
    certificates: 'digital',
    marketing: 'social-media',
    wasteSegregation: 'available',
    initiatives: ['tree-plantation', 'community-awareness', 'waste-recycling'],
  },
]

export default sampleEvents
